#!/bin/bash 

if [ -n "$1" ]
then 
echo "hello $1"
else 
echo "no parameters found"
fi 

echo "there was $# parameters used"
echo "the last parameter is ${!#}"


count=1

for param in "$*"
do 
echo "\$* param is $param"
done 

for param in "$@"
do 
echo "\$@ param #$count is $param"
count=$(( $count+1 ))
done 

